### ISSUE TITLE
Tidelift funding

### ISSUE THREAD

**Issue by phated** [sindresorhus/timed-out#18]
Hey @floatdrop!

It's been awhile! Thanks for all your work on gulp back in the day—your work still influences us to this day. 🙏 🎊 

Anyway, I just started at Tidelift and have been looking through our list of projects that have funding available and noticed some of your packages (list below). I’d love to get you signed up so we can start paying you this money.

* [timed-out has about $80 per month](https://tidelift.com/lifter/search/npm/timed-out)
* [is-retry-allowed has about $60 per month](https://tidelift.com/lifter/search/npm/is-retry-allowed)
* [require-from-string has about $45 per month](https://tidelift.com/lifter/search/npm/require-from-string)
* [create-error-class has almost $45 per month](https://tidelift.com/lifter/search/npm/create-error-class)
* [capture-stack-trace has about $15 per month](https://tidelift.com/lifter/search/npm/capture-stack-trace)

The high-level overview of Tidelift is that we sell a “managed open source” subscription to companies and pay that money out to maintainers. We use their dependency trees to determine which packages are depended upon and, therefore, should get the funds. You can read more about Tidelift’s subscription service [on our site](https://tidelift.com/subscription).

The tasks we ask you to perform are things that most maintainers already do (such as provide release notes, validate the license of a package, and monitor and alert for security vulnerabilities), but you can find the specific details in [this blog post](https://blog.tidelift.com/how-to-start-earning-money-for-your-open-source-project-with-tidelift) by @kszu.

Please let me know what you think! I’m happy to answer any other questions you might have. 😸 

Thanks for all your open source work,
-Blaine

**Comment by sindresorhus** [comment]
This repo is now transferred to me, so closing.
